# Generated by Django 3.2.5 on 2021-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdat',
            field=models.DateTimeField(default='2000-11-02'),
        ),
    ]
